#!/bin/sh
# /usr/bin/blurlock

# take screenshot
# import -window root /tmp/screenshot.png

# # blur it
# convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
# rm /tmp/screenshot.png

# # lock the screen
# i3lock -i /tmp/screenshotblur.png

(
  CURRENT_LAYOUT_GROUP=$(xkb-switch -p) \
  ; xkb-switch -s us \
  ; i3lock-fancy-rapid 2 pixel -n \
  ; xkb-switch -s $CURRENT_LAYOUT_GROUP
  ) &

# # sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
